/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGraphique;

import Model.Caillou;
import Model.Coordonnees;
import Model.Direction;
import Model.Jeton;
import Model.Joueur;
import Model.JoueurIA;
import Model.Monstre;
import Model.Partie;
import Model.Pion;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Corentin
 */
public class Fenster extends javax.swing.JFrame implements Vue {

    public static final String VERSION = "0.2";

    /**
     * Creates new form Fenste
     */
    public Fenster() {
        initComponents();
        this.getContentPane().setBackground(BG_COLOR);

        // this.updatePlateau();
        /*
            Là c'est des essais
         */
//        plateau.add(pionsPurple[0], new Integer(1));
//        pionsPurple[0].setLocation(106, 220);
//        pionsPurple[0].setOpaque(false);
//
//        int larg = 4;
//        int haut = 220;
//        for (int i = 1; i < 4; i++) {
//            plateau.add(pionsPurple[i], new Integer(1));
//            larg++;
//            pionsPurple[i].setLocation(plateau.position(new Coordonnees(6, larg)));
//            pionsPurple[i].setOpaque(false);
//        }
//
//        JFlaque flaque = new JFlaque(JFlaque.Forme.HORIZ);
//        flaque.setLocation(plateau.position(new Coordonnees(5, 6)));
//        flaque.setOpaque(false);
//        plateau.add(flaque, new Integer(0));
//        sortis.add(pionsGreen[1]);
//        sortis.add(pionsGreen[2]);
        //pionsGreen[1].setLocation(plateau.position(new Coordonnees(5, 1)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        champPseudoCo = new javax.swing.JTextField();
        champPseudoCrea = new javax.swing.JTextField();
        champMdpCrea = new javax.swing.JTextField();
        validerConnexion = new javax.swing.JButton();
        validerCreation = new javax.swing.JButton();
        champMdpCo = new javax.swing.JPasswordField();
        sortis = new JGroupePions(false);
        salleAttenteGreen = new JGroupePions(true);
        salleAttenteRed = new JGroupePions(true);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomJoueurRouge = new javax.swing.JLabel();
        nomJoueurVert = new javax.swing.JLabel();
        boutonEntrerPlateau = new javax.swing.JButton();
        boutonFinTour = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPartie = new javax.swing.JMenu();
        jMenuItemNewGame = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jDialog1.setPreferredSize(new java.awt.Dimension(500, 300));
        jDialog1.setResizable(false);

        jLabel3.setText("Connexion");

        jLabel4.setText("Créer un compte");

        jLabel5.setText("Pseudo");

        jLabel6.setText("Pseudo");

        jLabel7.setText("Mot de passe");

        jLabel8.setText("Mot de passe");

        champPseudoCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champPseudoCoActionPerformed(evt);
            }
        });

        champPseudoCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champPseudoCreaActionPerformed(evt);
            }
        });

        validerConnexion.setText("Valider");
        validerConnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validerConnexionMouseClicked(evt);
            }
        });

        validerCreation.setText("Valider");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(champMdpCo))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(champPseudoCo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(champPseudoCrea))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(27, 27, 27)
                        .addComponent(champMdpCrea, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(validerConnexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(validerCreation)
                .addGap(83, 83, 83))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(champPseudoCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(champPseudoCrea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(champMdpCrea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(champMdpCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validerConnexion)
                    .addComponent(validerCreation))
                .addGap(46, 46, 46))
        );

        jLabel4.getAccessibleContext().setAccessibleName("créationCompte");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Finstere Flure v" +this.VERSION);
        setFocusCycleRoot(false);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        sortis.setBackground(null);
        sortis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        sortis.setPreferredSize(new java.awt.Dimension(40, 374));

        javax.swing.GroupLayout sortisLayout = new javax.swing.GroupLayout(sortis);
        sortis.setLayout(sortisLayout);
        sortisLayout.setHorizontalGroup(
            sortisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        sortisLayout.setVerticalGroup(
            sortisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        salleAttenteGreen.setBackground(null);
        salleAttenteGreen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        salleAttenteGreen.setPreferredSize(new java.awt.Dimension(301, 40));

        javax.swing.GroupLayout salleAttenteGreenLayout = new javax.swing.GroupLayout(salleAttenteGreen);
        salleAttenteGreen.setLayout(salleAttenteGreenLayout);
        salleAttenteGreenLayout.setHorizontalGroup(
            salleAttenteGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        salleAttenteGreenLayout.setVerticalGroup(
            salleAttenteGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        salleAttenteRed.setBackground(null);
        salleAttenteRed.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        salleAttenteRed.setPreferredSize(new java.awt.Dimension(301, 40));

        javax.swing.GroupLayout salleAttenteRedLayout = new javax.swing.GroupLayout(salleAttenteRed);
        salleAttenteRed.setLayout(salleAttenteRedLayout);
        salleAttenteRedLayout.setHorizontalGroup(
            salleAttenteRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        salleAttenteRedLayout.setVerticalGroup(
            salleAttenteRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jLabel1.setText("Rouge :");

        jLabel2.setText("Vert :");

        boutonEntrerPlateau.setText("Entrer sur le plateau");
        boutonEntrerPlateau.setEnabled(false);

        boutonFinTour.setText("Terminer le tour");
        boutonFinTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonFinTourActionPerformed(evt);
            }
        });

        jMenuPartie.setText("Partie");
        jMenuPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPartieActionPerformed(evt);
            }
        });

        jMenuItemNewGame.setText("Nouvelle partie...");
        jMenuItemNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewGameActionPerformed(evt);
            }
        });
        jMenuPartie.add(jMenuItemNewGame);
        jMenuPartie.add(jSeparator1);

        jMenuItem2.setText("Historique");
        jMenuPartie.add(jMenuItem2);

        jMenuItem3.setText("Options");
        jMenuPartie.add(jMenuItem3);
        jMenuPartie.add(jSeparator2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Quitter");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuPartie.add(jMenuItem4);

        jMenuBar1.add(jMenuPartie);

        jMenuHelp.setText("?");

        jMenuItem5.setText("Aide");
        jMenuHelp.add(jMenuItem5);

        jMenuItem6.setText("A propos...");
        jMenuHelp.add(jMenuItem6);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(sortis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salleAttenteRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomJoueurRouge, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomJoueurVert, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(salleAttenteGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(boutonEntrerPlateau))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boutonFinTour)
                        .addGap(441, 441, 441)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(sortis, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salleAttenteRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salleAttenteGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(boutonEntrerPlateau)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nomJoueurRouge, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(nomJoueurVert, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(boutonFinTour)
                .addGap(72, 72, 72))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Detection de la pression d'une touche du clavier. Si c'est une des
     * flèches et qu'un pion est sélectionné, on essaye de déplacer ce pion dans
     * la direction de la flèche.
     *
     * @param evt
     */
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        Direction d = null;
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_DOWN:
                d = Direction.BAS;
                break;
            case KeyEvent.VK_UP:
                d = Direction.HAUT;
                break;
            case KeyEvent.VK_LEFT:
                d = Direction.GAUCHE;
                break;
            case KeyEvent.VK_RIGHT:
                d = Direction.DROITE;
                break;
        }

        if (selected != null && d != null) {

            /*
            METTRE ICI LES INSTRUCTIONS DE DEPLACEMENT
             */
            selected.setLocation(plateau.position(selected.getCoordonnees().plus(d.getVector())));
        }
    }//GEN-LAST:event_formKeyPressed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewGameActionPerformed
        String[] typePartie = {"2 joueurs", "contre l'ordinateur"};
        int rang = JOptionPane.showOptionDialog(null, "Quel type de partie voulez-vous jouer ?", "Type partie", JOptionPane.OK_CANCEL_OPTION, -1, null, typePartie, typePartie[0]);
        if (rang == 0) {//Si partie 2 joueurs
            /*
            APPELER 2 FOIS LA FENETRE D'AUTHENTIFICATION. CE SERAIT BIEN DE POUVOIR RECUPERER LE PSEUDO DU JOUEUR. EN CAS DERREUR DE MDP, ON PEUT AFFICHER UN POPUP D'ERREUR.
             */
            jDialog1.setVisible(true);
            initPartie();
        } else {//Si contre IA
            /*
            MEME CHOSE MAIS UNE SEULE FOIS, CAR IL N'Y A QU'UN JOUEUR
            */
            jDialog1.setVisible(true);
            initPartie();
        }

    }//GEN-LAST:event_jMenuItemNewGameActionPerformed

    private void jMenuPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPartieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuPartieActionPerformed

    private void boutonFinTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonFinTourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonFinTourActionPerformed

    private void champPseudoCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champPseudoCoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champPseudoCoActionPerformed

    private void champPseudoCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champPseudoCreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champPseudoCreaActionPerformed

    private void validerConnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerConnexionMouseClicked
        // TODO add your handling code here:
        String pseudo = champPseudoCo.getText();
        String mdp = champMdpCo.getText();
        boolean valide;
        //finir la fonction qui voit si un compte est valide ou pas
        valide = connexionIdent(pseudo, mdp);
    }//GEN-LAST:event_validerConnexionMouseClicked

    /**
     * Instructions à éxécuter quand on clique sur un pion : on le sélectionne
     *
     * @param evt
     */
    private void pionClicked(MouseEvent evt) {
        //vérifier que on a bien cliqué sur un de ses pions, et pas de l'adversaire
        JPion clicked = (JPion) evt.getSource();
        if (clicked.isEnabled() && clicked.getNumJoueur() == numJoueur && !dejaBouge) {

            this.selected.unselect();
            this.selected = clicked;
            this.selected.select();

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the STANDARD look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Fenster.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Fenster.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Fenster.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Fenster.class.getName()).log(Level.SEVERE, null, ex);
        }
//</editor-fold>
//</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenster().setVisible(true);
            }
        });
    }

    public void initPartie() {

        //Créer les 2 joueurs en fonction de la réposne
        this.partie = new Partie(this, j1, j2);

        this.nomJoueurRouge.setText(j1.getPseudo());
        this.nomJoueurVert.setText(j2.getPseudo());

        /*
        Création du monstre
         */
        String[] spritesMonstre = {"monstre1.gif", "monstre2.gif", "monstre3.gif", "monstre4.gif"};
        monstre = new JPion(spritesMonstre);
        monstre.setOpaque(false);

        /*
          Création des jetons joueurs avec ajout de leurs images
         */
        String[] adresses = {"pionred_1_6_clair.gif", "pionpurple_1_6_fonce.gif"};
        pionsPurple[0] = new JPion(adresses, 1);
        String[] adresses2 = {"pionred_3_4_clair.gif", "pionpurple_3_4_fonce.gif"};
        pionsPurple[1] = new JPion(adresses2, 1);
        String[] adresses3 = {"pionred_4_3_clair.gif", "pionpurple_4_3_fonce.gif"};
        pionsPurple[2] = new JPion(adresses3, 1);
        String[] adresses4 = {"pionred_5_2_clair.gif", "pionpurple_5_2_fonce.gif"};
        pionsPurple[3] = new JPion(adresses4, 1);

        String[] adresses5 = {"piongreen_1_6_clair.gif", "piongreen_1_6_fonce.gif"};
        pionsGreen[0] = new JPion(adresses5, 2);
        String[] adresses6 = {"piongreen_3_4_clair.gif", "piongreen_3_4_fonce.gif"};
        pionsGreen[1] = new JPion(adresses6, 2);
        String[] adresses7 = {"piongreen_4_3_clair.gif", "piongreen_4_3_fonce.gif"};
        pionsGreen[2] = new JPion(adresses7, 2);
        String[] adresses8 = {"piongreen_5_2_clair.gif", "piongreen_5_2_fonce.gif"};
        pionsGreen[3] = new JPion(adresses8, 2);

        /*
            A chaque jeton on ajoute un MouseListener afin de détecter un clic dessus, et on rend le pion transparent
         */
        for (JPion p : pionsPurple) {
            p.setOpaque(false);
            p.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    pionClicked(evt);
                }
            });
        }

        for (JPion p : pionsGreen) {
            p.setOpaque(false);
            p.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    pionClicked(evt);
                }
            });
        }

        /*
            Création et initialisation du plateau
         */
        plateau = new JPlateau();
        plateau.setBounds(100, 50, 694, 479);//permet de définir la position et la taille en même temps        
        this.add(plateau);

        updatePlateau();

        this.pack();
        this.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonEntrerPlateau;
    private javax.swing.JButton boutonFinTour;
    private javax.swing.JPasswordField champMdpCo;
    private javax.swing.JTextField champMdpCrea;
    private javax.swing.JTextField champPseudoCo;
    private javax.swing.JTextField champPseudoCrea;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemNewGame;
    private javax.swing.JMenu jMenuPartie;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel nomJoueurRouge;
    private javax.swing.JLabel nomJoueurVert;
    private javax.swing.JPanel salleAttenteGreen;
    private javax.swing.JPanel salleAttenteRed;
    private javax.swing.JPanel sortis;
    private javax.swing.JButton validerConnexion;
    private javax.swing.JButton validerCreation;
    // End of variables declaration//GEN-END:variables
    JPion[] pionsPurple = new JPion[4];
    JPion[] pionsGreen = new JPion[4];
    JPion monstre;
    JPlateau plateau;
    JPion selected = new JPion(new String[1]);

    int numJoueur;

    boolean dejaBouge; //Indique si le joueur a déjà commencé à bouger un pion. Si oui, il ne peut pas en sélectionner d'autre.

    public final Color BG_COLOR = new Color(220, 205, 245);

    Partie partie;

    /**
     * Met à jour le plateau et des salles d'attente et d'arrivée.
     */
    @Override
    public void updatePlateau() {

        //On supprime toutes les entités du plateau qui sont sur la couche 1 = tout sauf les tâches de sang
        Component[] pions = plateau.getComponentsInLayer(1);
        for (Component c : pions) {
            plateau.remove(c);
        }
        salleAttenteGreen.removeAll();
        salleAttenteRed.removeAll();

        //On affiche les jetons
        for (int i = 0; i < 4; i++) {
            Jeton jeton = this.partie.getJoueur1().getPions()[i];
            JPion jetonAffiche = pionsPurple[i];
            //On n'affiche que les pions vivants
            if (jeton.getVivant() && jeton.getEnJeu()) {//On ne met pas à jour les pions sortis car une fois qu'ils sont déjà sortis, ils peuvent pas aller ailleurs !! (cf. "Vous sortes !")
                if (jeton.getSurPlateau()) {
                    jetonAffiche.setLocation(plateau.position(jeton.getPosition()));

                    //Revoir s'il faut vérifier le sprite
                    plateau.add(jetonAffiche, new Integer(1));
                } else { //Le jeton est dans la réserve
                    salleAttenteRed.add(jetonAffiche);
                }

            }
        }

        for (int i = 0; i < 4; i++) {
            Jeton jeton = this.partie.getJoueur2().getPions()[i];
            JPion jetonAffiche = pionsGreen[i];
            //On n'affiche que les pions vivants
            if (jeton.getVivant() && jeton.getEnJeu()) {//On ne met pas à jour les pions sortis car une fois qu'ils sont déjà sortis, ils peuvent pas aller ailleurs !! (cf. "Vous sortes !")
                if (jeton.getSurPlateau()) {
                    jetonAffiche.setLocation(plateau.position(jeton.getPosition()));

                    //Revoir s'il faut vérifier le sprite
                    plateau.add(jetonAffiche, new Integer(1));
                } else { //Le jeton est dans la réserve
                    salleAttenteGreen.add(jetonAffiche);
                }

            }
        }

        //On parcourt le plateau du modèle
        for (Pion p : this.partie.getPlateau().getPlateau().values()) {

            //On affiche les cailloux
            if (p instanceof Caillou) {
                String[] sprite = new String[1];
                sprite[0] = "mur.png";
                JPion caillou = new JPion(sprite);//On créé un nouveau caillou
                caillou.setLocation(plateau.position(p.getPosition())); //plateau.position(Coordonnees c) est le convertisseur qui transforme les coordonnées en la position en pixels sur l'écran
                plateau.add(caillou, new Integer(1));

                //On affiche le monstre
            } else if (p instanceof Monstre) {
                Monstre m = (Monstre) p;//On est obligé de convertir en Monstre pour pouvoir utiliser getDirection()
                monstre.setLocation(plateau.position(p.getPosition()));
                switch (m.getDirection()) {//On attribue au monstre le sprite correspondant à sa direction
                    case HAUT:
                        monstre.setSprite(0);
                        break;
                    case DROITE:
                        monstre.setSprite(1);
                        break;
                    case BAS:
                        monstre.setSprite(2);
                        break;
                    case GAUCHE:
                        monstre.setSprite(3);
                        break;
                }
                plateau.add(monstre, new Integer(1));

            }
        }
    }

    @Override
    public void tourJoueur(int numJoueur) {
        dejaBouge = false;
        selected.unselect();
        this.selected = null;
        boutonFinTour.setEnabled(true);

        if (numJoueur == 1) {
            this.numJoueur = 1;
        } else if (numJoueur == 2) {
            this.numJoueur = 2;
        }
    }

}
